### PR TITLE
New project for use with ASP.Net MVC 6.

### PR DESCRIPTION
**Pull request by leedale1981**
Created new project for use with ASP.Net MVC 6. HTML Extensions are no longer used with MVC 6. Created a TagHelper for Line Chart to initially test out. Will create TagHelpers for all chart types

This project can be referenced in a MVC 6 RC1 web application and used with the TagHelper

### CODE REVIEW

**Comment by martinobordin** [comment]
Thanks for the pull request..could you please also migrate to chart.js 2.0? I don't have time right now to migrate :(

**Comment by leedale1981** [comment]
OK I'll have a look at migrating to version 2.0 for both MVC 5 and MVC 6. I also wanted to create a tag helper for each chart type.

**Comment by martinobordin** [comment]
Ok, that's fine for me..just keep the old _Html.CreateChart_ API and call it in the specialized helpers.

**Comment by martinobordin** [comment]
Hi @leedale1981, just wanted to figure out if you're working on migration to chart.js v2.

**Comment by leedale1981** [comment]
Hi I'm working on it bit slowly at the moment but will get there.

**Comment by martinobordin** [comment]
Ok thanks
Il 06 lug 2016 4:30 PM, "Lee Dale" notifications@github.com ha scritto:

**Comment by leedale1981** [comment]
Updated the project to now use ChartJS 2.2.2 and created a sample application and project for use with ASP.Net MVC 6 and .Net Core 1.0.  Still need to create more TagHelpers for the rest of the chart types.  May want to implement the new properties for the charts in 2.2.2 as well.

**Comment by martinobordin** [comment]
Thanks for the good work.. I'll update the nuget package and documentation soon

**Comment by leedale1981** [comment]
Cool nice one. Might need a new NuGet package for the MVC6 library? Although there is only a TagHelper for LineChart at the moment. Will be creating TagHelpers for the other charts very soon.

**Pull request merged**
