### PR TITLE
Created TagHelpers for all chart types

### PR DESCRIPTION
**Pull request by leedale1981**
Also created MVC6 .Net Core sample application showing all chart types.

### CODE REVIEW

**Comment by martinobordin** [comment]
Very good!

**Comment by freeborn5** [comment]
Do you want to skype now?

**Comment by leedale1981** [comment]
Should I go ahead and create a separate nuget package for the MVC 6 version?

**Comment by martinobordin** [comment]
For me it's ok. Something like Chart.Mvc.Core ?

**Pull request merged**
